# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            一杯时光半生缘
tagline:          '老板，给我一杯时光，让我忘掉忧伤！'
description:      '老板，给我一杯时光，让我忘掉忧伤！ Made by <a href="https://twitter.com/mdo" target="_blank">@kentwang</a>.'
url:              https://kentwang1403.github.io/
baseurl:''
paginate:             2
paginate_path:        'page-:num'
excerpt_separator:    <!--more-->

author:
  name:           'Kent Wang'
  url:            https://kentwang1403.github.io/

# Comment
comment:
    #disqus: 
    duoshuo:  xmuplusgithub

paginate:         3


github:
  repo:           https://github.com/poole/lanyon
