# Dependencies
#markdown:         redcarpet
#pygments:         true

# Permalinks
permalink:            pretty        #'/:title/'
relative_permalinks:  false

# Setup
title:            一杯时光半生缘
tagline:          '老板，给我一杯时光，让我忘掉忧伤！'
description:      '老板，给我一杯时光，让我忘掉忧伤！ Made by <a href="https://twitter.com/mdo" target="_blank">@kentwang</a>.'
url:              https://kentwang1403.github.io/

# About/contact
author:
  name:           
  url:            https://kentwang1403.github.io/

paginate:         2

# Comment
comment:
    #disqus: 
    duoshuo:  kentwang

#摘要
excerpt_separator:  '<!-- more -->

#github:
  #repo:           https://github.com/poole/lanyon
